[브루트포스] 9월 13일
Altu-Bitu-5/Altu-Bitu-KimSion pull request #4
Opened 2023-09-13 04:15 UTC by Zion2-6

###인적사항
학번: 2176060
이름: 김시온
</br>

###과제 제출
기존 제출: 1063, 1436, 11723

2023-09-15 08:44 UTC, Goldchae reviewed
**브루트 포스- 구현 문제 리뷰 완료!**
p2. main함수 말고도 다른 함수로 기능을 빼 주셔도 좋을 것 같습니다! 수고하셨어요!

2023-09-15 08:44 UTC, Goldchae commented on 04_브루트포스/1063.cpp
> +    string_to_integer["R"] = 1;
p3. switch문은 char형도 매개변수로 받을 수 있죠! 하지만 그런 경우에 2글자 문자열은 어떻게 처리할 수 있을지 코드를 바꿔야 할 것 같네요!

2023-09-15 08:44 UTC, Goldchae commented on 04_브루트포스/1063.cpp
> +int main() {
p3. main함수가 너무 길어서 코드에 가독성이 떨어지네요ㅜ 어떤 기능들을 묶어서 뺄 수 있을까요?

2023-09-15 08:44 UTC, Goldchae commented on 04_브루트포스/1063.cpp
> +        int king_x = king[0] - 'A';  // 킹의 열 위치를 숫자로 변환
p3. 열 위치를 숫자로 바꾸는 것 말고도 char형으로 다룰 수도 있습니다!

2023-09-15 08:44 UTC, Goldchae commented on 04_브루트포스/1063.cpp
> +        int stone_x = stone[0] - 'A';  // 돌의 열 위치를 숫자로 변환
주석 좋습니다!

2023-09-15 08:44 UTC, Goldchae commented on 04_브루트포스/1063.cpp
> +    cout << king << endl;
p3. endl과 \n 의 시간복잡도 차이는 10배가 넘게 납니다ㅜ 지금은 괜찮아도 나중에는 시간초과가 날 수 있으니 유의해주세요!

2023-09-15 09:46 UTC, kwakrhkr59 requested changes
**브루트포스 필수 알고리즘 코드리뷰 완료**
11723(P1) 안녕하세요 시온님~ 브뤁포스 필수 알고리즘 문제 코드 리뷰 완료되셨습니다! 다만 11723번이 백준에서 시간 초과가 떠 통과되고 있지 않는 것으로 확인됩니다...! 백준에서 정답입니다가 뜨지 않는 코드는 제출로 인정이 안되니 **반드시** 확인 후 재제출해주세요! 다시 제출하신 후 리뷰어로 호출해주시면 확인해드리도록 하겠습니다😀

2023-09-15 09:46 UTC, kwakrhkr59 commented on 04_브루트포스/11723.cpp
> +            S.reset();  // 모든 비트를 0으로 설정
P1. 이 문제는 집합에서 연산을 묻는 문제이지만 애석하게도 bitset을 사용해서는 풀 수 없는 문제입니다😂 비트를 활용한다는 점은 잘 체크해주셨지만 bitset이 아닌 int의 32개 비트 중 20개를 사용하는 식으로 사용해주셔야 해요! 지금 코드로는 시간초과가 나네요😥 백준에서 통과되지 않는 코드는 제출해주셔도 과제 제출로 인정이 되지 않으니 꼭 확인하신 후 수정해서 제출해주세요❗❗❗

2023-09-15 09:46 UTC, kwakrhkr59 commented on 04_브루트포스/1436.cpp
> +        if (to_string(end_num).find("666") != string::npos) {
end_num을 string으로 바꾸지 않아도 666을 찾을 수 있어요! 한 정수가 주어져있울 때 각 자릿수를 접근하고 싶을 때 이 숫자를 10씩 나눠가며 나머지를 확인했던 거 기억하시나요? 여기서도 마찬가지로, 대신 666이라는 세자리 숫자를 확인해야 하니 1000으로 나눴을 때의 나머지를 확인하면 666의 존재를 찾을 수 있어요! 샘플 코드에는 이 방식으로 풀이가 되어 있으니 한 번 확인해보셔도 좋을 것 같습니다😁

2023-09-15 09:46 UTC, kwakrhkr59 commented on 04_브루트포스/1436.cpp
> +    }
이 부분은 함수화 해주셔도 좋을 것 같아요!

2023-09-19 04:20 UTC, kwakrhkr59 approved these changes
안녕하세요 시온님~ 11723번 재제출 확인되셨습니다! 수고 많으셨습니다😊 이제 머지하셔도 좋습니다!

2023-09-20 02:13 UTC, merged